name: cc-core
version: '1.0'
main: net.cc.core.CorePlugin
description: WIP
api-version: '1.21.4'
load: STARTUP
authors: [ SpektrSoyuz ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true
    SayanVanish:
      load: BEFORE
      required: true
      join-classpath: true